### ISSUE TITLE
Segmentation fault when trying recursion

### ISSUE THREAD

**Issue by RZED786** [DynamicSquid/Night#24]
I was trying to make a 99 bottles of beer program for Rosetta Code. I used a recursive function but it gave me a segmentation fault.
This was my code:
```
null bottles(int x) {
  if(x == 1) {
    print("1 bottle of beer on the wall,\n");
    print("1 bottle of beer,\n");
    print("Take it down, pass it around,\n");
    print("No more bottles of beer.\n");
  }
  else {
    print(x);
    print(" bottles of beer on the wall,\n");
    print(x);
    print(" bottles of beer,\n");
    print("Take one down, pass it around,\n");
    print(x - 1);
    print(" bottles of beer on the wall,");
    bottles(x-1);
  }
}
bottles(99);
```
When I get rid of the recursive call, there is no segmentation fault, but nothing is printed (Neither the if statement or the else statement are working). I know you are working on arrays now so you can leave this until v3.0 or later if you want. In the mean time I will just replace it with a loop.

**Comment by DynamicSquid** [comment]
Yeah I had the same problem with recursion as well. Keep in mind that `v2` is still in beta and not all the features work properly. Also loops won't work either cause they are static. The loop condition only evaluates once, but all this will change (hopefully) in `v3` (coming out soon) since that will be my first non-beta release.

**Comment by DynamicSquid** [comment]
That's for reporting it to me though!
