### ISSUE TITLE
Favicon icon and meta tags of documentation page.

### ISSUE THREAD

**Issue by kimlimjustin** [DynamicSquid/night#70]
Hello, I've been visiting the Night documentation page and I've noticed that there's no favicon icon and meta tags for the website. I strongly suggest putting a favicon icon and meta tags for the documentation site to increase the SEO of the page. I would like to be assigned for this issue :)

**Comment by DynamicSquid** [comment]
Thanks for taking interest! I really appreciate it!

However that's the old website, and I'm currently working on a [new one](https://dynamicsquid.github.io/night/), which does have a favicon. It's hosted with GitHub pages and the code is in the docs folder. But it's not close to being finished yet, so that's why I chose to show to old one instead of the new one.

Progress is a little slow on the new website since I'm busy working on the actual language, so if you have any suggestions or comments for the new website, I'd love to hear it!

Sorry if this is a little confusing, I haven't really done a good job of updating the GitHub page.

**Comment by kimlimjustin** [comment]
Ohh okay
